src/Entity/Chapter.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ChapterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChapterRepository::class)]
#[ApiResource]
class Chapter
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $chapter_title = null;

    #[ORM\Column]
    private ?int $chapter_position = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $chapter_content = null;


    /**
     * @var Collection<int, Course>
     */
    #[ORM\OneToMany(targetEntity: Course::class, mappedBy: 'chapter')]
    private Collection $id_course;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'chapters')]
    private Collection $users;



    public function __construct()
    {
        $this->id_course = new ArrayCollection();
        $this->users = new ArrayCollection();
        
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChapterTitle(): ?string
    {
        return $this->chapter_title;
    }

    public function setChapterTitle(string $chapter_title): static
    {
        $this->chapter_title = $chapter_title;

        return $this;
    }

    public function getChapterPosition(): ?int
    {
        return $this->chapter_position;
    }

    public function setChapterPosition(int $chapter_position): static
    {
        $this->chapter_position = $chapter_position;

        return $this;
    }

    public function getChapterContent(): ?string
    {
        return $this->chapter_content;
    }

    public function setChapterContent(string $chapter_content): static
    {
        $this->chapter_content = $chapter_content;

        return $this;
    }

    /**
     * @return Collection<int, Course>
     */
    public function getIdCourse(): Collection
    {
        return $this->id_course;
    }

    public function addIdCourse(Course $idCourse): static
    {
        if (!$this->id_course->contains($idCourse)) {
            $this->id_course->add($idCourse);
            $idCourse->setChapter($this);
        }

        return $this;
    }

    public function removeIdCourse(Course $idCourse): static
    {
        if ($this->id_course->removeElement($idCourse)) {
            // set the owning side to null (unless already changed)
            if ($idCourse->getChapter() === $this) {
                $idCourse->setChapter(null);
            }
        }

        return $this;
    }

    public function __tostring(){
        return $this->getChapterTitle();
    }

    // public function getByPosition(){
        
    //     return $this->getChapterPosition(
    //                     'group_by' => function(Chapter $chapter, $key, $value) {
    //                         return $chapter->getType()->getName();
    //                     };


    //     );
    // }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    
}

src/Controller/ApiManagementController.php
<?php

namespace App\Controller;

use App\Repository\ChapterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\SerializerInterface;

#[Route('/access', name: 'app_api_')]
final class ApiManagementController extends AbstractController
{
    #[Route('/management', name: 'management')]
    public function index(): Response
    {
        return $this->render('api_management/index.html.twig', [
            'controller_name' => 'ApiManagementController',
        ]);
   }
   #[Route('/chapters', name: 'show_chapters_list', methods: ['GET'])]
    public function listChapters(ChapterRepository $chapterRepository, SerializerInterface $serializer): Response
    {
        $chapters = $chapterRepository->findAll();
        // $jsonChapters = $serializer->serialize($chapters, 'json');
        // return new JsonResponse($jsonChapters, Response::HTTP_OK, ['Content-Type' => 'application/json'], true);
        return $this->render('api_management/chapters.html.twig', [
            'chapter_name' => 'Chapter List',
            'chapters'=> $chapters,
        ]);
    }
}

templates/api_management/chapters.html.twig
{% extends 'base.html.twig' %}

{% block title %}Api: Chapters{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{chapter_name}}✅</h1>
</div>
<div class="setionChapters">
    <div class="partTitle">
        <h3 class="titleChapters">
            Les chapitres disponible : 
        </h3>
    </div>
    <div class="partChapters">
        {% for chapter in chapters %}
        <div class="review-item">
            <ul>
                <li>{{ chapter.chapterTitle }}</li>
            </ul>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/api_management/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Api Controller!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>
</div>
<div>
    <a class="btnChapterUnit" href="{{ path('app_api_show_chapters_list')}}"> Chapitres </a>
</div>
{% endblock %}